datasets:
  gender:
    column_mapping:
      categorical_features:
       - numerical
      numerical_features: [ ]
      target: gender
    data_format:
      header: true
      separator: ','
    monitors:
      - classification_performance
      - data_drift
      - cat_target_drift
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5