data:
    path: "./data/train_revised.csv"
    test_path: "./data/val_revised.csv"
train:
    ngram: [3,4]
test:
    run_id: "2a47f4923cc34c589b00773f75168747"
optimize:
    bayes_opt: !!bool False
    max_evals: 10
