apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidently
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evidently
  template:
    metadata:
      labels:
        app: evidently #tag to find service
    spec:
      containers:
      - name: evidently
        image: gender-revised_evidently_service:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8085
        env:
        - name: PROMETHEUS_ADDRESS
          value: http://prometheus.default.svc.cluster.local:9090
        - name: EVIDENTLY_SERVICE
          value: http://evidently.default.svc.cluster.local:8085
        volumeMounts:
        - name: evidently-data
          mountPath: /app/datasets
      volumes:
      - name: evidently-data
        hostPath:
          path: /home/rsa-key-20221205/gender-revised/datasets