apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 2345
        env:
        - name: GF_SERVER_HTTP_PORT
          value: '2345'
        - name: PROMETHEUS_ADDRESS
          value: http://prometheus.default.svc.cluster.local:9090
        - name: EVIDENTLY_SERVICE
          value: http://evidently.default.svc.cluster.local:8085
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-config-datasources
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-config-dashboards
        - name: grafana-dashboards
          mountPath: /opt/grafana/dashboards/classification_performance.json
          subPath: classification_performance.json
        - name: grafana-drift
          mountPath: /opt/grafana/dashboards/data_drift.json
          subPath: data_drift.json
        - name: grafana-data
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-data
        emptyDir: {}
      - name: grafana-dashboards
        configMap:
          defaultMode: 420
          name: json-configmap
      - name: grafana-drift
        configMap:
          defaultMode: 420
          name: drift-configmap
      - name: grafana-config-dashboards
        configMap:
          defaultMode: 420
          name: grafana-config-dashboards
      - name: grafana-config-datasources
        configMap:
          defaultMode: 420
          name: grafana-config-datasources
