apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-datasources
  namespace: default
data:
  grafana_datasources.yaml: |-
    {
        "apiVersion": 1,
        "deleteDatasources": [
            {
                "name": "Prometheus",
                "orgId": 1
            }
        ],
        "datasources": [
            {
                "access":"proxy",
                "name": "Prometheus",
                "type": "prometheus",
                "url": "http://prometheus.default.svc.cluster.local:9090"
            }
        ]
    }