version: '3.7'

services:
  pgdatabase:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: "gender_data"
    volumes:
      - ./postgres/gender_postgres:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin/gender_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"