name: CI-Tests
on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '/home/rsa-key-20221205/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install dependencies
        working-directory: "/home/rsa-key-20221205/"
        run: pip install requirements.txt

      - name: Run Unit tests
        working-directory: "/home/rsa-key-20221205/"
        run: pytest tests/

      - name: Lint
        working-directory: "/home/rsa-key-20221205/"
        run: pylint --recursive=y .

      - name: Integration Test
        working-directory: '/home/rsa-key-20221205/gender-revised/'
        run: |
          . run.sh
